import AppBar from "@/components/Appbar";
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
export default function ProductsLayout({ children }) {
    return (
        <html lang="en">
            <body >
              {children}
                product page Layout
                
            </body>
        </html>
    )
}